export const data = {
  acoustic_model: "assemblyai_default",
  audio_duration: 331,
  audio_end_at: null,
  audio_start_from: null,
  audio_url:
    "https://cdn.assemblyai.com/upload/99b9ada4-578a-4f0f-99ed-ab5b4a31d70b",
  auto_chapters: true,
  auto_highlights: false,
  auto_highlights_result: null,
  boost_param: null,
  confidence: 0.923570053900785,
  content_safety: false,
  content_safety_labels: {
    results: [],
    status: "unavailable",
    summary: {},
  },
  disfluencies: true,
  dual_channel: null,
  entities: null,
  entity_detection: false,
  filter_profanity: false,
  format_text: true,
  iab_categories: false,
  iab_categories_result: {
    results: [],
    status: "unavailable",
    summary: {},
  },
  id: "or1atkkfdm-6fb2-4250-bc3a-0284f70dc5a9",
  language_code: "en_us",
  language_model: "assemblyai_default",
  punctuate: true,
  redact_pii: false,
  redact_pii_audio: false,
  redact_pii_audio_quality: null,
  redact_pii_policies: null,
  redact_pii_sub: null,
  sentiment_analysis: true,
  sentiment_analysis_results: [
    {
      confidence: 0.7474468946456909,
      end: 1400,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 430,
      text: "Section two.",
    },
    {
      confidence: 0.8661434650421143,
      end: 10950,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 2090,
      text: "You will hear a customer services official giving information to a passenger at a railway station in a town called Traborch.",
    },
    {
      confidence: 0.8825770616531372,
      end: 32010,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 11750,
      text: "First you have some time to look at questions eleven to 17.",
    },
    {
      confidence: 0.8512102365493774,
      end: 51790,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 32020,
      text: "Now listen carefully and answer questions eleven to 17.",
    },
    {
      confidence: 0.5208579301834106,
      end: 55840,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 55090,
      text: "Hello.",
    },
    {
      confidence: 0.8638880848884583,
      end: 62920,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 56280,
      text: "Um, my family and I are staying here in Trabrich for a week or two and we wanted to know about the train services.",
    },
    {
      confidence: 0.7343418002128601,
      end: 65550,
      sentiment: "POSITIVE",
      speaker: null,
      start: 63370,
      text: "We're hoping to do a few local trips.",
    },
    {
      confidence: 0.7984716892242432,
      end: 72230,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 65730,
      text: "Okay, well, I can give you lots of details about all the trains going from Traborch in the Southwest.",
    },
    {
      confidence: 0.8820593953132629,
      end: 77642,
      sentiment: "POSITIVE",
      speaker: null,
      start: 72610,
      text: "This leaflet will be very helpful, but I can tell you some of the main things.",
    },
    {
      confidence: 0.879443347454071,
      end: 81006,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 77836,
      text: "We've got two main train stations in the town.",
    },
    {
      confidence: 0.9201910495758057,
      end: 85480,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 81138,
      text: "The King Street is for local commuter lines and um, regional services.",
    },
    {
      confidence: 0.8941200375556946,
      end: 88074,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 85990,
      text: "What about trains to London?",
    },
    {
      confidence: 0.6869248747825623,
      end: 90794,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 88242,
      text: "I'll need to go there on business for one day.",
    },
    {
      confidence: 0.8665692806243896,
      end: 93174,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 90952,
      text: "Then you need to go to Central Station.",
    },
    {
      confidence: 0.7773255109786987,
      end: 95620,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 93342,
      text: "That's for all the national services.",
    },
    {
      confidence: 0.8317651152610779,
      end: 97986,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 96010,
      text: "There are regular trains to London.",
    },
    {
      confidence: 0.925629198551178,
      end: 103686,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 98118,
      text: "They leave Treburch every half hour on weekdays and every hour at weekends.",
    },
    {
      confidence: 0.7204066514968872,
      end: 112094,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 103878,
      text: "It takes about 2 hours, a bit longer on Sundays you've got a choice of first and second class and there's a buffet car.",
    },
    {
      confidence: 0.9066667556762695,
      end: 116334,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 112252,
      text: "The refreshments are included in the cost of a first class ticket.",
    },
    {
      confidence: 0.5664749145507812,
      end: 117220,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 116502,
      text: "Right.",
    },
    {
      confidence: 0.9034209847450256,
      end: 121770,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 117730,
      text: "And have you got any information on different ticket types?",
    },
    {
      confidence: 0.8782811164855957,
      end: 128870,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 121890,
      text: "Yes, there's a range of ticket prices depending on when you travel and when you buy your ticket.",
    },
    {
      confidence: 0.7872664928436279,
      end: 134130,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 129190,
      text: "There's a standard open ticket which doesn't have any restrictions.",
    },
    {
      confidence: 0.87199866771698,
      end: 137620,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 134310,
      text: "This can be bought in advance or on the day.",
    },
    {
      confidence: 0.6567280292510986,
      end: 141534,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 137950,
      text: "You can also get various discounted tickets.",
    },
    {
      confidence: 0.8652769923210144,
      end: 148600,
      sentiment: "POSITIVE",
      speaker: null,
      start: 141702,
      text: "A popular one is called the Super Save and this uh, is okay for travel after 845.",
    },
    {
      confidence: 0.68608558177948,
      end: 154860,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 149530,
      text: "Then that is the special ticket which is valid for travel after 1015.",
    },
    {
      confidence: 0.6209278106689453,
      end: 159470,
      sentiment: "POSITIVE",
      speaker: null,
      start: 154870,
      text: "The special tickets are also valid for travel at weekends.",
    },
    {
      confidence: 0.8253083825111389,
      end: 166660,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 159970,
      text: "The cheapest tickets are called advance and you have to buy them at least six days ahead.",
    },
    {
      confidence: 0.784153401851654,
      end: 178426,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 167170,
      text: "Only a certain number are available and um, you have to make seat reservations for these before you hear the rest of the conversation.",
    },
    {
      confidence: 0.858638346195221,
      end: 182780,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 178618,
      text: "You have some time to look at questions 18 to 20.",
    },
    {
      confidence: 0.6440993547439575,
      end: 190800,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 190760,
      text: "Mhm.",
    },
    {
      confidence: 0.8777238726615906,
      end: 201780,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 197730,
      text: "Now listen and answer questions 18 to 20.",
    },
    {
      confidence: 0.6283754110336304,
      end: 206114,
      sentiment: "POSITIVE",
      speaker: null,
      start: 205390,
      text: "Thanks.",
    },
    {
      confidence: 0.7535329461097717,
      end: 209954,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 206272,
      text: "And are there lots of places to go to around here?",
    },
    {
      confidence: 0.9593315720558167,
      end: 213880,
      sentiment: "POSITIVE",
      speaker: null,
      start: 210112,
      text: "Oh yes, you can enjoy many days out.",
    },
    {
      confidence: 0.6349772214889526,
      end: 220780,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 214500,
      text: "Um, there's the Mercer Mining Museum which is only half an hour from Tuberch by train.",
    },
    {
      confidence: 0.9767258763313293,
      end: 225498,
      sentiment: "POSITIVE",
      speaker: null,
      start: 221170,
      text: "Your children will find it just as fascinating as any theme park.",
    },
    {
      confidence: 0.8578364253044128,
      end: 228774,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 225594,
      text: "And they can ride in the original miners lifts.",
    },
    {
      confidence: 0.8362468481063843,
      end: 235050,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 228822,
      text: "And on the coal trains there are special excursion tickets which include entrance fees.",
    },
    {
      confidence: 0.9195088148117065,
      end: 248210,
      sentiment: "POSITIVE",
      speaker: null,
      start: 235230,
      text: "Mainline trains also offer direct services to Bristol where you can visit the docks or spend a great day out with the children in the Zoo which is set in the Parkland that used to surround the Old Castle.",
    },
    {
      confidence: 0.8890255689620972,
      end: 254450,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 248770,
      text: "Special family away day fares are available for this service now during the school holidays.",
    },
    {
      confidence: 0.8725263476371765,
      end: 268614,
      sentiment: "POSITIVE",
      speaker: null,
      start: 255250,
      text: "Alternatively, you can be in Birmingham, um, in only an hour and a half where there's lots to see and do including the new and internationally acclaimed climbing wall built on the site of the old aquarium.",
    },
    {
      confidence: 0.5625253319740295,
      end: 275318,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 268782,
      text: "We will also be running a special service to Newport when the new science Museum opens next year.",
    },
    {
      confidence: 0.7119725346565247,
      end: 282426,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 275464,
      text: "As we anticipate a lot to visitors in the opening weeks I'd advise you to call early to book your tickets.",
    },
    {
      confidence: 0.8209019899368286,
      end: 283622,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 282618,
      text: "Is that okay?",
    },
    {
      confidence: 0.4610389769077301,
      end: 284090,
      sentiment: "POSITIVE",
      speaker: null,
      start: 283756,
      text: "Yes.",
    },
    {
      confidence: 0.6283754110336304,
      end: 284740,
      sentiment: "POSITIVE",
      speaker: null,
      start: 284140,
      text: "Thanks.",
    },
    {
      confidence: 0.8422678709030151,
      end: 290180,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 287930,
      text: "That's is the end of section two.",
    },
    {
      confidence: 0.7730345726013184,
      end: 294270,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 290630,
      text: "You now have half a minute to check your answers.",
    },
    {
      confidence: 0.8345386385917664,
      end: 325880,
      sentiment: "NEUTRAL",
      speaker: null,
      start: 324310,
      text: "Now turn to section three.",
    },
  ],
  speaker_labels: false,
  speed_boost: false,
  status: "completed",
  text: "Section two. You will hear a customer services official giving information to a passenger at a railway station in a town called Traborch. First you have some time to look at questions eleven to 17. Now listen carefully and answer questions eleven to 17. Hello. Um, my family and I are staying here in Trabrich for a week or two and we wanted to know about the train services. We're hoping to do a few local trips. Okay, well, I can give you lots of details about all the trains going from Traborch in the Southwest. This leaflet will be very helpful, but I can tell you some of the main things. We've got two main train stations in the town. The King Street is for local commuter lines and um, regional services. What about trains to London? I'll need to go there on business for one day. Then you need to go to Central Station. That's for all the national services. There are regular trains to London. They leave Treburch every half hour on weekdays and every hour at weekends. It takes about 2 hours, a bit longer on Sundays you've got a choice of first and second class and there's a buffet car. The refreshments are included in the cost of a first class ticket. Right. And have you got any information on different ticket types? Yes, there's a range of ticket prices depending on when you travel and when you buy your ticket. There's a standard open ticket which doesn't have any restrictions. This can be bought in advance or on the day. You can also get various discounted tickets. A popular one is called the Super Save and this uh, is okay for travel after 845. Then that is the special ticket which is valid for travel after 1015. The special tickets are also valid for travel at weekends. The cheapest tickets are called advance and you have to buy them at least six days ahead. Only a certain number are available and um, you have to make seat reservations for these before you hear the rest of the conversation. You have some time to look at questions 18 to 20. Mhm. Now listen and answer questions 18 to 20. Thanks. And are there lots of places to go to around here? Oh yes, you can enjoy many days out. Um, there's the Mercer Mining Museum which is only half an hour from Tuberch by train. Your children will find it just as fascinating as any theme park. And they can ride in the original miners lifts. And on the coal trains there are special excursion tickets which include entrance fees. Mainline trains also offer direct services to Bristol where you can visit the docks or spend a great day out with the children in the Zoo which is set in the Parkland that used to surround the Old Castle. Special family away day fares are available for this service now during the school holidays. Alternatively, you can be in Birmingham, um, in only an hour and a half where there's lots to see and do including the new and internationally acclaimed climbing wall built on the site of the old aquarium. We will also be running a special service to Newport when the new science Museum opens next year. As we anticipate a lot to visitors in the opening weeks I'd advise you to call early to book your tickets. Is that okay? Yes. Thanks. That's is the end of section two. You now have half a minute to check your answers. Now turn to section three.",
  utterances: null,
  webhook_status_code: null,
  webhook_url: null,
  word_boost: [],
};
